name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Docker/Dockerfile --tag jobet:$(date +%s)

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npx eslint .

    - name: ESLint Init
      run: npx eslint --init @eslint/config

    - name: Check formatting with Prettier
      run: npm run prettier

    - name: Run build
      run: npm run dev

    - name: Run tests
      run: npm run test
